name: check cleared outputs, format and lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  check_outputs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ensure cleared outputs
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
  format:
    needs: check_outputs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: format
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: check_formatting
  flake8:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint with flake8
        uses: mhitza/flake8-jupyter-notebook@v1
